version: '3.8'

services:
    mysql: # @Rename
        container_name: app_mysql # @Rename
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app # @Rename
            MYSQL_USER: app
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
    php:
        container_name: app_php # @Rename
        build:
            context: ./docker/php
            args:
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/symfony-api # @Rename
        depends_on:
            - mysql
    nginx:
        container_name: app_nginx # @Rename
        image: nginx:stable-alpine # @Rename
        ports:
            - 8080:80
        volumes:
            - .:/var/www/symfony-api # @Rename
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
